services:
  backend:
    container_name: otahub-backend
    build: ./backend/otahub
    ports:
      - "8000:8000"
    volumes:
      - ./backend/otahub:/app
    env_file:
      - ./backend/otahub/.env
    environment:
      - DEBUG=1
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
  
  frontend:
    container_name: otahub-frontend
    build: ./frontend/otahub-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/otahub-frontend:/app
      - /app/node_modules
    depends_on:
      - backend
